### PR TITLE
feat: add gitpod setup & change readme

### LINKED ISSUE #136: Setup gitpod and write a readme documentation
Something like this would be amazing. Screenshot taken from cal.com's readme
CleanShot 2024-02-21 at 22 47 47

https://github.com/calcom/cal.com?tab=readme-ov-file#gitpod-setup

### PR DESCRIPTION
**Pull request by anikdhabal**
fixes #136 

Add gitpod setup and write readme documentation.

### CODE REVIEW

**Review by dahal — CHANGES_REQUESTED** [review]
Amazing work on this @anikdhabal, however I am running into this error. I do see you are copying .env.example before the build.

Also, how does DB and SMTP connection really work with gitpod?


CleanShot 2024-02-28 at 22 25 54

**Comment by anikdhabal** [comment]
Hey @dahal, thanks for the review. I noticed that you haven't been updating the .env.example and .gitpod.yml files during setup. You're encountering this error because when you open our repository in Gitpod, it automatically adds certain commands and a .gitpod.yml file and starts automatically.

So, could you please update the .env example and .gitpod.yml files? After updating the .gitpod.yml file, you should see a popup to validate the commands. After clicking it, validate our commands and redirect to a different page with the updated code setup.

Also, we receive all emails in Inbucket, which is accessible on port 9000.

**Review by dahal — APPROVED** [review]
> Hey @dahal, thanks for the review. I noticed that you haven't been updating the .env.example and .gitpod.yml files during setup. You're encountering this error because when you open our repository in Gitpod, it automatically adds certain commands and a .gitpod.yml file and starts automatically.
> 
> So, could you please update the .env example and .gitpod.yml files? After updating the .gitpod.yml file, you should see a popup to validate the commands. After clicking it, validate our commands and redirect to a different page with the updated code setup.
> 
> Also, we receive all emails in Inbucket, which is accessible on port 9000.

Oh, thanks for the clarification, I didnot think of that. I initially clicked on the button which links to `opencapco/opencap.co` 's `main` and it does not have the updated .gitpod.yml 🤦‍♂️

Testing with your fork/branch worked. 🎉, this is amazing @anikdhabal , keep up the good work 👏👏👏

**Comment by anikdhabal** [comment]
> > Hey @dahal, thanks for the review. I noticed that you haven't been updating the .env.example and .gitpod.yml files during setup. You're encountering this error because when you open our repository in Gitpod, it automatically adds certain commands and a .gitpod.yml file and starts automatically.
> > So, could you please update the .env example and .gitpod.yml files? After updating the .gitpod.yml file, you should see a popup to validate the commands. After clicking it, validate our commands and redirect to a different page with the updated code setup.
> > Also, we receive all emails in Inbucket, which is accessible on port 9000.
> 
> Oh, thanks for the clarification, I didnot think of that. I initially clicked on the button which links to `opencapco/opencap.co` 's `main` and it does not have the updated .gitpod.yml 🤦‍♂️
> 
> Testing with your fork/branch worked. 🎉, this is amazing @anikdhabal , keep up the good work 👏👏👏

Thank you🙏. I will do my best from my side.

**Pull request merged**
