### PR TITLE
feat: add invite member feature

### PR DESCRIPTION
**Pull request by G3root**
fixes:  #35

### CODE REVIEW

**Comment by G3root** [comment]
@dahal ready for review

**Comment by G3root** [comment]
converting to draft as some features are missing

**Comment by G3root** [comment]
ready for review

**Comment by G3root** [comment]
currently implemented

- user can invite a user through email
- user can join a company using a link
- user can see their members and invitations
- user can remove a member or revoke invite link

**Review by jeremyscatigna — APPROVED** [review]
Looking really clean 🚀

**Pull request merged**
