### PR TITLE
feat: Create one stakeholder

### LINKED ISSUE #208: Create one stakeholder
CleanShot 2024-03-22 at 03 58 15

Currently this button triggers a modal to upload stakeholders in bulk and here is what the csv template look like

CleanShot 2024-03-22 at 03 59 19

Convert this button to a [`DropdownButton`](https://github.com/opencapco/opencap.co/blob/main/src/components/ui/dropdown-button.tsx) with two options

* Create one stakeholder
* Import multiple stakeholders

Create one stakeholder should open a modal (we already have a shared modal component) with all the inputs on the attached screenshot/template.

import multiple stakeholders should open the existing bulk upload modal.

### PR DESCRIPTION
**Pull request by anikdhabal**
fixes #208

### CODE REVIEW

**Comment by anikdhabal** [comment]
cc @dahal

**Review by dahal — CHANGES_REQUESTED** [review]
I am running into a strange issue, on all inputs. It does not let you type space

For example 

CleanShot 2024-04-01 at 00 17 04

**Comment by anikdhabal** [comment]
> I am running into a strange issue, on all inputs. It does not let you type space
> 
> For example
> 
> CleanShot 2024-04-01 at 00 17 04

Thanks for the review.

**Review by dahal — APPROVED** [review]
🫡

**Pull request merged**
