### PR TITLE
chore: add docker compose for easy dev setup

### PR DESCRIPTION
**Pull request by dephraiim**

### CODE REVIEW

**Review by tedspare — APPROVED** [review]
LGTM

How can I test the changes? Check out the branch, ensure Docker is running, and run `docker compose up` in the root dir?

**Comment by dahal** [comment]
> LGTM
> 
> How can I test the changes? Check out the branch, ensure Docker is running, and run `docker compose up` in the root dir?

@tedspare That sounds about right

Thanks for dockerizing @dephraiim . We should work on one click deploy to fly/render after this is good to go.

**Comment by dephraiim** [comment]
@tedspare the correct command should be `npm run docker:start`

**Comment by tedspare** [comment]
> @tedspare the correct command should be `npm run docker:start`

Thanks, tested the DB locally and all looks good. For docs:
- Run Docker
- Instantiate the DB: `bun db:start`
- Generate tables: `prisma generate && prisma migrate dev`
- Run Prisma studio to see the local DB via GUI: `bun db:studio`
- Run the web app: `bun dev`
- Open the web app in the browser and join the waitlist. Should see a new row in the DB.

image
image

**Pull request merged**
