### PR TITLE
feat: add signining document feature

### PR DESCRIPTION
**Pull request by G3root**

### CODE REVIEW

**Comment by G3root** [comment]
@dahal here's the current state of this PR

- text field are implemented and can be rendered on the uploaded pdf

### things to do
- implement signature field

### known issues
- positioning currently doesn't work as expected for pdf's with uneven page height, the current algorithm need some small tinkering.

[Screencast 2024-02-28 22:27:53.webm](https://github.com/opencapco/opencap.co/assets/84864519/a43cb85d-ed9e-4560-a2f3-3441c5f6a60d)

**Comment by G3root** [comment]
Any feedback is appreciated

**Review by dahal — CHANGES_REQUESTED** [review]
Its looking great @G3root. Great job 🫡



I assume you are going to fill these input/canvas as well right?

CleanShot 2024-02-28 at 22 38 43


Also, when scrolling document while signing, lets make that right hand side input card fixed/sticky as well

**Review by dahal — CHANGES_REQUESTED** [review]
@G3root looks like creating a template feature is broken. I could not test the signing without creating the template.

**Review by dahal — APPROVED** [review]
This is looking really good, more optimization coming soon 😻

**Pull request merged**
