### PR TITLE
feat: New SAFEs with y-combinator and custom template

### LINKED ISSUE #178: Create a new SAFE with YC template and custom template
* I have already created schema, and a multi-step modal for this feature to get started with

CleanShot 2024-03-19 at 01 53 50

* Please implement all the following (steps are on comment) input fields and steps.
* YC SAFEs are currently on `public/yc` directory.
* If user has picked from one of these templates, remove the document step, if they have picked `CUSTOM` as an option on `SAFE template` selector, show them the document step.

If they have picked YC template
* Upload the template to their document repository (Upload on a private bucket)
* Redirect them to `/:publicId/templates/:documentId` so they can configure the template for eSign

CleanShot 2024-03-19 at 02 01 44

If they have picked `CUSTOM` during `SAFE template` selector
* Show the documents step
* Do not allow `multiple = {false}`
* Title should be, `Upload the custom SAFE template`
* After the upload, redirect them to `/:publicId/templates/:documentId`

> Note: this PR is not going to do any esigning features/fixes.

> ~eSign is currently being worked on by @G3root~ - Complete for this use case
> ~Multi-step modal is being worked on by @Aashish-Upadhyay-101~ - Complete

### PR DESCRIPTION
**Pull request by Raju-kadel-27**
fixes #178

### CODE REVIEW

**Comment by Raju-kadel-27** [comment]
@dahal @chetannn  I think it's ready for review ?

**Review by dahal — CHANGES_REQUESTED** [review]
Here are few errors I ran into

* Build errors with `./procedures/get-safes` and `./procedures/delete-safe` no defined.
* Template upload error

image

**Comment by Raju-kadel-27** [comment]
@dahal I have push those procedures. You can try once.

**Comment by Raju-kadel-27** [comment]
> Here are few errors I ran into
> 
> * Build errors with `./procedures/get-safes` and `./procedures/delete-safe` no defined.
> * Template upload error
> 
> image

okay, I will resolve it.

**Comment by Raju-kadel-27** [comment]
@dahal I think errors are resolved ?

**Review by dahal — APPROVED** [review]
🚀

**Pull request merged**
